docker:
        memory_size: "2048"
        image: "bigtop/ssh:centos-6.4"

boot2docker:
        memory_size: "4196"
        number_cpus: "2"

namenode_ui_port: "50070"
yarn_ui_port: "8088"
hbase_ui_port: "60010"
