# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "boot2docker" do |node|
    node.vm.box = "yungsang/boot2docker"
    node.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", CONF["boot2docker"]["memory_size"]]
    end
    node.vm.network "forwarded_port", host: CONF["namenode_ui_port"], guest: 50070
    node.vm.network "forwarded_port", host: CONF["yarn_ui_port"], guest: 8088
    node.vm.network "forwarded_port", host: CONF["hbase_ui_port"], guest: 60010
  end

end
