# -*- mode: ruby -*-
# vi: set ft=ruby :

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ENV['VAGRANT_DEFAULT_PROVIDER'] ||= 'docker'

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # number of instances
  $num_instances = 3

  # declare the variable first, will be override in following loop
  $bigtop_master = ""

  # nodes definition
  (1..$num_instances).each do |i|
    config.vm.define "bigtop#{i}" do |bigtop|

      $bigtop_hostname="bigtop#{i}.docker"
      if "#{i}" == "1"
        $bigtop_master = $bigtop_hostname
      end

      # docker container settings
      bigtop.vm.provider "docker" do |d|
        d.image = "bigtop/hadoop:centos-6.4"
	d.name = "bigtop#{i}"
        d.privileged = true
        if "#{i}" == "1"
	  d.ports = ["50070:50070","8088:8088","60010:60010"]
        end
	d.has_ssh = true
      end

      bigtop.ssh.username = "root"
      bigtop.ssh.port = 22
      bigtop.vm.hostname = $bigtop_hostname

      # shell provisioner to setup basic vm environment
      bigtop.vm.provision :shell do |shell|
        shell.path = "provision.sh"
        shell.args = $bigtop_master + " " + $bigtop_hostname
      end

      bigtop.vm.provision :hostmanager

      if "#{i}" == "1"
        bigtop.vm.provision :shell do |shell|
          shell.path = "init-master.sh"
        end
      else
        bigtop.vm.provision :shell do |shell|
          shell.path = "init-slave.sh"
        end
      end
    end
  end

end
